version: '3'
services:
  db:
    image: postgres
    volumes:
      - /tmp/db:/var/postgresql/data
  web:
    build: .
    command: bundle exec rails s -p 3000 '0.0.0.0'
    volumes: eposcomp
    ports:
      - "3000:3000"
    depends_on:
      - db
